---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: heading
  label: Content
- type: document
  path: src/index.md
  label: Homepage
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "*.md"
  templates:
  - page-detail
- type: directory
  path: src/cases
  label: Cases
  create: documents
  match: "*.md"
  templates:
  - page-detail
- type: heading
  label: Global
- type: document
  path: src/_data/navigation.json
  label: Navigatie
- type: document
  path: src/_data/site.json
  label: Website settings
upload_dir: src/assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start
